#!/bin/bash

if [[ -z $1 ]] || [[ $1 == "debug" ]]; then
    echo "DEBUG BUILD"
    BUILD_MODE=debug
elif [[ $1 == "release" ]]; then
    echo "RELEASE BUILD"
    BUILD_MODE=release
else
    echo "INVALID BUILD"
    exit 1
fi

make clean
mkdir build
yacc -y -d grammar/grammar.y || exit 1
lex grammar/tokens.l || exit 1
make $BUILD_MODE -j
