#!/bin/bash

PROG_NAME=$1

if [[ -z $CC ]]; then
    which musl-gcc
    FOUND_MUSL_GCC=$?
    if [[ $FOUND_MUSL_GCC == 0 ]]; then
        FLAGS=-'static -Wall -Wextra -Werror -Wno-unused-variable -std=c89'
        CC="musl-gcc $FLAGS"
    else
        CC='cc'
    fi
fi

echo "CC=${CC}"

./boa example/$PROG_NAME.boa

clang-format -i example/$PROG_NAME.c || true

$CC -Os example/$PROG_NAME.c libruntime.a -o bin/$PROG_NAME

./bin/$PROG_NAME
