#!/bin/bash

PROG_NAME=$1

set -e

if [[ -z $CC ]]; then
    which musl-gcc
    FOUND_MUSL_GCC=$?
    if [[ $FOUND_MUSL_GCC == 0 ]]; then
       CC='musl-gcc -static'
   else
       CC='cc'
    fi
fi

echo "CC=${CC}"

./boa example/$PROG_NAME.boa

clang-format -i example/$PROG_NAME.c || true

$CC -Os -Wall -Wextra -Wpedantic -Werror -Wno-unused-variable \
    example/$PROG_NAME.c libruntime.a -o bin/$PROG_NAME

./bin/$PROG_NAME
